services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transplant-app
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5001
    volumes:
      - ./app-data:/app/data
    restart: always
